### ISSUE TITLE
"vue add capacitor@next" throws errors

### ISSUE THREAD

**Issue by birgerstoeckelmann** [nklayman/vue-cli-plugin-capacitor#1]
Hi,

running "vue add capacitory@next" in the vue CLI 3 project folder gives me errors:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for vue-cli-plugin-capacitor@next
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

I'm using npm 6.5.0.

How do I install the right package? "vue add capacitor" installs https://github.com/techiediaries/vue-cli-plugin-capacitor.

Thanks!

**Comment by nklayman** [comment]
Currently, this plugin is not published, I am waiting on [this issue](https://github.com/techiediaries/vue-cli-plugin-capacitor/issues/1) to publish it. For now, just install it with `npm i -D nklayman/vue-cli-plugin-capacitor`, and invoke it with `vue invoke capacitor`. I will update the readme accordingly.
