### ISSUE TITLE
Lost plugin:generate command

### ISSUE THREAD

**Issue by AlanGreyjoy** [nklayman/vue-cli-plugin-capacitor#10]
When I type 'npx @capacitor/cli plugin:generate' console hangs for about 2 seconds, and then nothing happens. I suspect using this vue-cli plugin has something to do with it. Any advice?

**Comment by nklayman** [comment]
I think the generate command should be run outside of the Vue cli app folder. Since the plugin is its own package it shouldn't be nested under your Vue app. Try running it in a different dir and see if that helps.

**Comment by AlanGreyjoy** [comment]
Agreed.
