### ISSUE TITLE
Should we add to version control each env folder?

### ISSUE THREAD

**Issue by dobromir-hristov** [nklayman/vue-cli-plugin-capacitor#4]
Hi,
The plugin made adding capacitor a breeze. 

I wanted to ask should we add the `android`  folder for example to version control? 

Asking because I inspected and saw it is augmenting the `capacitor.config.js` every time we `serve` or `build`, which I get is necessary, but it injects data that is only relevant to my env (paths or IPs).

Thanks!

**Comment by nklayman** [comment]
Capacitor should add a `.gitignore` file to the platform folders, and everything not in the gitignore should be checked in to source control.

**Comment by dobromir-hristov** [comment]
Yeah, but the serve and build commands change the config and add data only relevant to my local env. Like paths or local URLs.

But yeah, thanks for your work.
