### ISSUE TITLE
Running a command just after build

### ISSUE THREAD

**Issue by dobromir-hristov** [nklayman/vue-cli-plugin-capacitor#5]
To be able to use the Ionic AppFlow service, a manifest file needs to be created from the generated files, which is done via `ionic deploy manifest`.

Can we add a way to run a custom command right after the build command? Because I tried without it, and the deployment fails.

Maybe a config inside `pluginOptions` in `vue.config.js`?
```
pluginOptions: {
    outputDir: '',
    capacitorScripts: {
      postbuild: 'custom --thing',
    },
```

I tried searching for a way to run a command on every `vue-cli-service build`, but didnt find anything.

**Comment by nklayman** [comment]
See if the solution [here](https://forum.vuejs.org/t/register-a-plugin-service-command-as-a-post-build-hook/44711) works for you. It uses a webpack plugin to run code after the build completes. If that doesn't work I can add a postbuild hook.

**Comment by dobromir-hristov** [comment]
Yeah, used `webpack-shell-plugin-next` plugin, as it was fastest :)
Thanks for the tip.
