### ISSUE TITLE
Update to Capactor 2

### ISSUE THREAD

**Issue by santicros** [nklayman/vue-cli-plugin-capacitor#7]
Thanks for the really great plugin!
Could you update it so it uses Capacitor 2 version?

Thanks!

**Comment by nklayman** [comment]
Version 0.3.0+ of this plugin will use capacitor v2.0 for new projects. To upgrade existing projects, follow the upgrade guide section of the [capacitor 2.0 release announcement](https://ionicframework.com/blog/announcing-capacitor-2-0/).
