### ISSUE TITLE
Flag to skip standard vue cli build

### ISSUE THREAD

**Issue by richardmward** [nklayman/vue-cli-plugin-capacitor#8]
Just wondering what your thoughts on having a flag that could skip the vue cli build part of the `"capacitor:build"` script. I build the android app as part of a larger pipeline, and the app has already been built by this stage, so it seems unnecessary to run it again (unless it does something different and I didn't realise it?)

```
// Build app with Vue CLI
await api.service.run('build', args)
```

**Comment by nklayman** [comment]
Available in `0.4.0` with the `--skipBundle` arg.
